# Generated by Django 3.1.4 on 2020-12-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='lists',
        ),
    ]
