# Generated by Django 3.1.4 on 2020-12-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepage', '0002_auto_20201206_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='getlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getid', models.IntegerField(verbose_name='購入したアイテムの番号')),
                ('get', models.CharField(max_length=50, verbose_name='購入したアイテムの数')),
                ('discord', models.CharField(max_length=50, verbose_name='購入した人のdiscord(#あり)')),
                ('mcid', models.CharField(max_length=50, verbose_name='購入した人のmcid')),
                ('tantou', models.CharField(max_length=50, verbose_name='担当者(mcid)')),
                ('okno', models.CharField(choices=[('対応済み', 'ok'), ('非対応', 'no')], max_length=50, verbose_name='対応済みか')),
            ],
        ),
        migrations.AlterField(
            model_name='lists',
            name='money',
            field=models.IntegerField(verbose_name='金額'),
        ),
    ]
