# Generated by Django 3.1.4 on 2020-12-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepage', '0003_auto_20201207_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='getlist',
            name='getname',
            field=models.CharField(default=None, max_length=50, verbose_name='購入したアイテムの名前'),
            preserve_default=False,
        ),
    ]
