# Generated by Django 3.1.4 on 2020-12-06 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepage', '0004_getlist_getname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getlist',
            name='getname',
        ),
    ]
