# Generated by Django 3.1.4 on 2020-12-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepage', '0006_getlist_getname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getlist',
            name='getname',
        ),
        migrations.RemoveField(
            model_name='getlist',
            name='okno',
        ),
        migrations.RemoveField(
            model_name='getlist',
            name='tantou',
        ),
        migrations.AlterField(
            model_name='getlist',
            name='discord',
            field=models.CharField(max_length=50, verbose_name='discord(例)ヨッピ太郎#1234)'),
        ),
        migrations.AlterField(
            model_name='getlist',
            name='get',
            field=models.CharField(max_length=50, verbose_name='アイテム数(例)1LC1st1個)'),
        ),
        migrations.AlterField(
            model_name='getlist',
            name='getid',
            field=models.IntegerField(verbose_name='アイテムid(date/数字←この番号を入力してください)'),
        ),
        migrations.AlterField(
            model_name='getlist',
            name='mcid',
            field=models.CharField(max_length=50, verbose_name='mcid(例)Yoppychan)'),
        ),
    ]
